name: au_hostel_flow
description: A prototype hostel flow Flutter app.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/admin_background.png
    - assets/images/library_background.png
    - assets/images/au_logo.png
